import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getSettings } from "@/lib/actionsSettings";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const settings = await getSettings();
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full h-[100dvh] flex gap-5">
          <aside className="h-full w-/1/3 bg-red-500 p-5">
            {settings.WebsiteName}
          </aside>
          <main className="p-5">{children}</main>
        </div>
      </body>
    </html>
  );
}
